### PR TITLE
collectd: added to playbook and inventory

### PR DESCRIPTION
**Pull request by sandrobonazzola**
Added collectd role to playbook and inventory

Signed-off-by: Sandro Bonazzola sbonazzo@redhat.com

### CODE REVIEW

**Review by mrunge — DISMISSED** [review]

**Review by paramite — COMMENTED** [review]
You need to also add:

[collectd_hosts:children]
pm_hosts

**Comment by mrunge** [comment]
@sandrobonazzola could you please add the changes @paramite requested?

**Comment by sandrobonazzola** [comment]
@mrunge added @paramite requested changes.

**Comment by sandrobonazzola** [comment]
Any other change required on my side?

**Review by mrunge — APPROVED** [review]

**Pull request merged**
